[phases.setup]
nixPkgs = ['nodejs']

[phases.install]
cmds = ['bundle install', 'npm install --legacy-peer-deps']

[phases.build]
cmds = ['bundle exec rails assets:precompile']

[start]
cmd = 'bin/rails server -b 0.0.0.0 -p ${PORT:-3000}'
